.assist" commandName="Quick Assist - Rename in file" description="Invokes quick assist and selects 'Rename in file'" category="_kwynE35zEeuBffpV9revMw"/>
  <commands xmi:id="_kwx-S35zEeuBffpV9revMw" elementId="org.eclipse.debug.ui.commands.toggleMemoryMonitorsPane" commandName="Toggle Memory Monitors Pane" description="Toggle visibility of the Memory Monitors Pane" category="_kwynHX5zEeuBffpV9revMw"/>
  <commands xmi:id="_kwx-TH5zEeuBffpV9revMw" elementId="org.eclipse.jdt.ui.edit.text.java.search.implementors.in.working.set" commandName="Implementors in Working Set" description="Search for implementors of the selected interface in a working set" category="_kwynPX5zEeuBffpV9revMw"/>
  <commands xmi:id="_kwx-TX5zEeuBffpV9revMw" elementId="org.eclipse.egit.ui.team.Discard" commandName="Replace with File in Index" category="_kwynPn5zEeuBffpV9revMw"/>
  <commands xmi:id="_kwx-Tn5zEeuBffpV9revMw" elementId="org.eclipse.datatools.sqltools.sqleditor.refreshFromDatabaseAction" commandName="Refresh from Database" category="_kwynP35zEeuBffpV9revMw"/>
  <commands xmi:id="_kwx-T35zEeuBffpV9revMw" elementId="org.eclipse.datatools.sqltools.sqleditor.ExecuteAsOneStatementAction" commandName="Execute Selected Text As One Statement" category="_kwynP35zEeuBffpV9revMw"/>
  <commands xmi:id="_kwx-UH5zEeuBffpV9revMw" elementId="org.eclipse.egit.ui.RepositoriesViewCreateBranch" commandName="Create Branch..." category="_kwynPn5zEeuBffpV9revMw"/>
  <commands xmi:id="_kwx-UX5zEeuBffpV9revMw" elementId="org.eclipse.cft.server.ui.internal.actions.pushcommand" commandName="Push" description="Push application" category="_kwynJ35zEeuBffpV9revMw"/>
  <commands xmi:id="_kwx-Un5zEeuBffpV9revMw" elementId="org.eclipse.datatools.connectivity.commands.addrepository" commandName="New Repository Profile Command" description="Command to create a new repository profile" category="_kwynJ35zEeuBffpV9revMw"/>
  <commands xmi:id="_kwx-U35zEeuBffpV9revMw" elementId="org.eclipse.egit.ui.RepositoriesViewCopyPath" commandName=