.eclipse.wst.jsdt.ui.edit.text.java.extract.constant" commandName="Extract Constant" description="Extracts a constant into a new static var and uses the new static var" category="_kwynKH5zEeuBffpV9revMw"/>
  <commands xmi:id="_kwx-YH5zEeuBffpV9revMw" elementId="org.eclipse.datatools.sqltools.result.removeAllInstances" commandName="Remove All Visible Results" category="_kwynG35zEeuBffpV9revMw"/>
  <commands xmi:id="_kwx-YX5zEeuBffpV9revMw" elementId="org.eclipse.jdt.ui.edit.text.java.search.implement.occurrences" commandName="Search Implement Occurrences in File" description="Search for implement occurrences of a selected type" category="_kwynPX5zEeuBffpV9revMw"/>
  <commands xmi:id="_kwx-Yn5zEeuBffpV9revMw" elementId="org.eclipse.egit.ui.history.DeleteBranch" commandName="Delete Branch" category="_kwynJ35zEeuBffpV9revMw"/>
  <commands xmi:id="_kwx-Y35zEeuBffpV9revMw" elementId="org.eclipse.ui.edit.text.contentAssist.contextInformation" commandName="Context Information" description="Show Context Information" category="_kwynDn5zEeuBffpV9revMw"/>
  <commands xmi:id="_kwx-ZH5zEeuBffpV9revMw" elementId="org.eclipse.ui.file.saveAs" commandName="Save As" description="Save the current contents to another location" category="_kwynGH5zEeuBffpV9revMw"/>
  <commands xmi:id="_kwx-ZX5zEeuBffpV9revMw" elementId="org.eclipse.wst.jsdt.ui.edit.text.java.search.read.access.in.workspace" commandName="Read Access in Workspace" description="Search for read references to the selected element in the workspace" category="_kwynPX5zEeuBffpV9revMw"/>
  <commands xmi:id="_kwx-Zn5zEeuBffpV9revMw" elementId="org.eclipse.ui.window.previousPerspective" commandName="Previous Perspective" description="Switch to the previous perspective" category="_kwynGn5zEeuBffpV9revMw"/>
  <commands xmi:id="_kwx-Z35zEeuBffpV9revMw" elementId="org.eclipse.ui.window.splitEditor" commandName="Toggle Split Editor" description="Split or join the currently active editor." category="_kwynGn5zEeuBffpV9revMw">
    <parameters xmi:id="_kwx-aH5zEeuBffpV9revMw" elementId="Splitter.isHorizontal" name="Orientation" optional="false"/>
  </commands>
  <commands xmi:id="_kwx-aX5zEeuBffpV9revMw" elementId="org.eclipse.ui.navigate.collapseAll" commandName="Collapse All" description="Collapse the current tree" category="_kwynMX5zEeuBffpV9revMw"/>
  <commands xmi:id="_kwx-an5zEeuBffpV9revMw" elementId="org.eclipse.compare.copyAllRightToLeft" commandName="Copy All from Right to Left" description="Copy All Changes from Right to Left" category="_kwynNX5zEeuBffpV9revMw"/>
  <commands xmi:id="_kwx-a35zEeuBffpV9revMw" elementId="org.eclipse.mylyn.tasks.ui.command.deactivateSelectedTask" commandName="Deactivate Selected Task" category="_kwynMX5zEeuBffpV9revMw"/>
  <commands xmi:id="_kwx-bH5zEeuBffpV9revMw" elementId="org.eclipse.ui.window.lockToolBar" commandName="Toggle Lock Toolbars" description="Toggle the Lock on the Toolbars" category="_kwynGn5zEeuBffpV9revMw"