1	Digital by Default		MIMEAPRINCIPLE001	Business	High	Services should be accessible and delivered digitally as the preferred option.	By digitizing_ministry can provide services that meet the evolving expectations of customers and employees even in a period of tight budgets and complex challenges. Not only do users prefer digital services and interactions with ministry_but digital services can also empower them and broaden their engagement with ministry. In addition_for ministry_digitization reduces wastage of valuable resources and simplifies the administration_presenting an agile face of the ministry to the end user.	Digitizing requires ministry’s attention to three major considerations.\
i_The first is the core capabilities that ministry uses to engage users and carry out its work_the methods and tools it uses to provide services_the processes it implements_its approach to making decisions_and its sharing and publishing of useful data.\
ii_The second consideration is the organizational enablers that support ministry in delivering these capabilities_strategy;governance and organization;and leadership_talent_and culture.\
iii_The third requires ministry establish electronic channels and digitized processes for digital delivery of services_including machine-readable information_as the preferred option_while still keeping other channels open for those who are disconnected by choice or necessity.									1900-01-01	1900-01-01			1	umerkhan	2022-07-04	10:21:25	 	 	 	Create	1	\N	2022-07-04 10:21:25
2	Value for Money		MIMEAPRINCIPLE002	Business	High	Ministry business initiatives and investments must represent value for money and return a business benefit.	A service that does not have an understood return on investment_ROI_is unlikely to receive the on-going support and commitment that will make it sustainable. \
It is essential for the ministry to meet the following rules_value for money_encouraging competition_efficient_effective and ethical use of resources_and\
accountability and transparency.	1_Business initiatives will need to be fit for purpose and deliver value and benefit.\
2_Ministry will need to assess the ROI for each business initiative.\
3_A thorough understanding of the costs and benefits is required to establish an appropriate investment model to support the creation and on-going management of the service.\
4_A total cost of ownership_TCO_approach will be required to assess the investment against other priorities.\
5_The value and cost of investments need to be measurable in objective terms.									1900-01-01	1900-01-01			1	umerkhan	2022-07-04	10:21:25	 	 	 	Create	1	\N	2022-07-04 10:21:25
3	Enterprise Architecture Approval		MIMEAPRINCIPLE003	Business	High	All projects_programs and strategic changes are subject to enterprise architecture approval at key stages throughout the delivery lifecycle.	Rationale This ensures that projects_changes collectively move in the business and technology direction that are required by the ministry’s EA. This also controls and prevents divergence from strategic intent and helps understand the trade-offs around any divergence.	1_Develop and operate strategically aligned enterprise architecture_EA_that encompasses multiple domains – business;data;application;technology and information security. The stakeholders’ requirements from both business and technology should provide the basis for the foundation of enterprise architecture.\
2_Changes should be aligned with the future architecture state of the ministry.\
3_Changes to the architecture need to be formally managed so that divergence is controlled.\
4_Exceptions may be granted on the understanding that re-alignment can be achieved at some future date through an approved plan of action. Dispensations would normally be granted for a limited duration only.									1900-01-01	1900-01-01			1	umerkhan	2022-07-04	10:21:25	 	 	 	Create	1	\N	2022-07-04 10:21:25
4	Business Agility		MIMEAPRINCIPLE004	Business	High	Capabilities including business processes_information_applications_and technology assets are able to quickly evolve and adapt to a changing environment.	ministry services need to evolve and adapt without requiring being re-created. With the emergence of cloud services_the ministry needs to promote the use of agile development_services need to be designed to adapt for change_leading to a more rapid and cost-effective reaction_including business assessment and deployment_to changing requirements. 	1_Ministry must adopt approaches that are more agile.\
2_Ministry should be able to adapt to changing environments_such as increased user demand_business improvement_and technical innovation.\
3_Ministry should be able to respond successfully and rapidly to changes. \
4_Ministry should spend more time and effort on analysis of long-term needs and trends.\
5_Ministry needs to focus on business-centric_loosely coupled_service-oriented design_e.g. the use of design patterns_rules engines and so on. \
									1900-01-01	1900-01-01			1	umerkhan	2022-07-04	10:21:25	 	 	 	Create	1	\N	2022-07-04 10:21:25
5	Business Continuity		MIMEAPRINCIPLE005	Business	High	All business services and activities across the ministry should be operational in spite of systems failures and interruptions.	This protects the ministry in the event that all or part of its operations and_or computer services are rendered unusable. Planning and preparation for business continuity ensure that the ministry overcomes serious incidents or disasters and resumes its normal operations within a reasonably short period.	1_Risks of business interruption must be established in advance and managed. Management includes_but is not limited to_periodic reviews_testing for vulnerability and exposure_or designing mission-critical services to ensure business function continuity through redundant or alternative capabilities.\
2_Risk management and mitigation plan will need to be developed.\
3_Recoverability_redundancy_and maintainability should be addressed at the time of design.\
4_Applications must be assessed for criticality_impact on the ministry’s mission_to determine what level of continuity is required_and what corresponding recovery plan is necessary.									1900-01-01	1900-01-01			1	umerkhan	2022-07-04	10:21:25	 	 	 	Create	1	\N	2022-07-04 10:21:25
6	Ensure Compliance with Relevant Laws_Policies and Standards		MIMEAPRINCIPLE006	Business	High	All IT systems and related processes must comply with the applicable laws_policies and standards. They must also comply with the internal policies and principles_including the EA principles and policies.	Alignment to government regulations is mandatory for compliance_while alignment to internal policies is critical to drive homogeneity in the IT landscape and ministry priorities. Moreover_lack of compliance can lead to unforeseen liabilities and litigation that could otherwise be avoided.	1_Ministry is accountable for the way it manages information and IT services and assets.\
2_Ministry should ensure that employees are educated and aware of compliance requirements in relation to the use of IT services and assets.\
3_Compliance requirements across the ministry are consistent_comprehensive_actively monitored and reported and regularly reviewed.\
4_Ministry shall ensure that all regulatory and compliance requirements are clearly documented_accessible and known across the ministry.\
5_The highest competent authority shall approve any exceptions.									1900-01-01	1900-01-01			1	umerkhan	2022-07-04	10:21:25	 	 	 	Create	1	\N	2022-07-04 10:21:25
7	Uniform Data Governance and Assigned Data Ownership		MIMEAPRINCIPLE007	Data	High	A uniform data governance model across ministry shall be adopted with clearly identified data governance roles and processes. Each data asset at the ministry has business owner accountable for that information classification and quality.	Without data governance_an organization is unaware of its data landscape_how well it is protected and how much value it bears.\
Moreover_Data owners are in the best position to define the criticality and sensitivity of the information which sets the basis for classification and can update such information if the status of the information changes.\
	1_Data governance will be implemented through a set of policies_roles_and processes.\
2_Data governance and management will need extensive training and change management for the stakeholders and roles will ideally be filled up with a long term perspective\
3_Owners of each data asset at the ministry level must be assigned.\
4_Without data ownership and classification_it will be difficult for the information security team to define the level and nature of protection needed for each asset.  The situation could lead to one of the following outcomes_4.1_Lack of protection\
4.2_Under protection\
4.3_Over-protection\
5_Ministry must define and publicize policies_processes_and guidelines for information classification and ownership to assist information owners to understand their responsibility and perform their duties correctly.									1900-01-01	1900-01-01			1	umerkhan	2022-07-04	10:21:25	 	 	 	Create	1	\N	2022-07-04 10:21:25
8	Single Source of Truth and Seamless Data Sharing		MIMEAPRINCIPLE008	Data	High	Data is shared across all departments and functions within the ministry so that data once captured can be utilized to the maximum_while restricting any unauthorized access to data.	There will be a single source of truth and a homogeneous meaning for each data entity_throughout the ministry_to drive confidence in data and ease the effort to maintain data\
Timely capture of data and then reusing it enhances user experience_as users no longer submit the same data multiple times__enhances data integrity_as shared data is used across applications_and significantly reduces cost. It is less expensive to maintain data in a single application and share than to maintain duplicate information in multiple applications. The more seamlessly data is shared within the organization_the better it promotes a data-driven culture.\
	1_All data elements shall have the same meaning across the ministry. This will need the creation and maintenance of a ministry-wide Data Dictionary.\
2_Ministry shall maintain data elements in the shared information system_or one application to start with_and sharing the data with all applications_instead of having multiple applications maintain the same data element.\
3_Application design shall maximize the reuse of data_especially shared data_thus minimizing data input requirements from the end-users.\
4_A comprehensive data sharing policy shall be developed that shall define the principles_standards_and mechanisms for sharing of data within the ministry_between different applications_and externally_open data_sharing with other government bodies and sharing with global entities_.									1900-01-01	1900-01-01			1	umerkhan	2022-07-04	10:21:25	 	 	 	Create	1	\N	2022-07-04 10:21:25
9	Data is Trustworthy		MIMEAPRINCIPLE009	Data	High	Data and data services are reliable_accurate_relevant_timely and of high integrity.	Reliable information_data_services and systems that provide consistent outcomes help to reduce complaints_reviews_and appeals from users_consequently improve value.	1_Ministry needs to deliver information_which users can rely upon.\
2_Good processes create good data.  Processes need to be the focus of ongoing continuous improvement_which in turn will improve reliability_accuracy_relevancy_and timeliness_.\
3_Ministry needs to devote significantly greater effort towards data quality_business continuity_and business process design to ensure reliable information and information systems.									1900-01-01	1900-01-01			1	umerkhan	2022-07-04	10:21:25	 	 	 	Create	1	\N	2022-07-04 10:21:25
10	Common Use Applications		MIMEAPRINCIPLE010	Application	High	The same application is preferred across ministry rather than similar or duplicative applications_which are only provided to a subset of the ministry.	Duplicative capability is expensive in terms of both CAPEX and OPEX and proliferates conflicting data. 	1_Departments in ministry_which depend on the application_s__which does not serve the entire ministry_must change over to ministry-wide application_s_.\
2_ministry departments should not be allowed to develop an application for their own use that is similar or duplicative of ministry-wide application.									1900-01-01	1900-01-01			1	umerkhan	2022-07-04	10:21:25	 	 	 	Create	1	\N	2022-07-04 10:21:25
11	Technology Neutral		MIMEAPRINCIPLE011	Application	High	Applications are independent of specific vendor and technology choices and therefore can operate on a variety of vendor and technology.	The choice for different technologies will provide the application’s ability to run on multiple hardware and platforms.\
Independence of applications from the underlying technology allows applications to be developed_upgraded_and operated in the most cost-effective and timely way.\
Realizing that every decision made with respect to IT creates a dependency on the underlying technology_the intent of this principle is to ensure that business application software is not dependent on specific hardware and operating system.\
	1_This principle will require standards that support portability. \
2_Subsystem interfaces will need to be developed to enable legacy applications to interoperate with applications and operating environments developed under the enterprise architecture.\
3_Middleware should be used to decouple applications from specific hardware and operating systems.									1900-01-01	1900-01-01			1	umerkhan	2022-07-04	10:21:25	 	 	 	Create	1	\N	2022-07-04 10:21:25
12	Ease of Use		MIMEAPRINCIPLE012	Application	High	Applications are easy to use so that users can concentrate on their tasks without boggling about the underlying technology and implementation.	An intuitive_consistent and easy to use interface enhances user experience and improves stickiness.\
The more a user has to understand the underlying technology_the less productive that user is. Ease-of-use encourages users to work within the integrated information environment instead of developing isolated systems to accomplish the task outside of the ministry_s integrated information environment. Most of the knowledge required to operate one system will be similar to others. Training is kept to a minimum_and the risk of using a system improperly is low.\
	1_Applications are required to have a common "look-and-feel" and support ergonomic requirements. Hence_the common look-and-feel standard must be designed and usability test criteria must be developed. \
2_Guidelines for user interfaces should not be constrained by narrow assumptions about user location_language_systems training_or physical capability. Factors such as linguistics_customer physical infirmities_visual acuity_ability to use keyboard_mouse__and proficiency in the use of technology have broad ramifications in determining the ease-of-use of an application.\
3_Applications should have both Arabic and English easily switchable interfaces_wherever applicable.									1900-01-01	1900-01-01			1	umerkhan	2022-07-04	10:21:25	 	 	 	Create	1	\N	2022-07-04 10:21:25
13	Cloud First		MIMEAPRINCIPLE013	Technology	High	Think cloud first approach. This could be a private cloud_hosted cloud using commercial stacks or open stack_or a public cloud_STC_AWS or Azure etc._or a combination.	Digital systems are expected to be ubiquitous systems across geographies and locations. Digital systems are also expected to be agile and flexible. Cloud-based services and deployments enable flexibility_agility_scalability and performance to deliver services.	1_Not every IT service will be appropriate for delivery via the cloud.\
2_Evaluation criteria need to be created to provide the basis for an assessment model that can be used to justify cloud decisions.\
3_ministry must adopt the ITSM best practices.\
4_Cloud services must not be procured directly by business teams. This can unintentionally introduce unnecessary OPEX costs and inhibit reuse.									1900-01-01	1900-01-01			1	umerkhan	2022-07-04	10:21:25	 	 	 	Create	1	\N	2022-07-04 10:21:25
14	Technology Standardization		MIMEAPRINCIPLE014	Technology	High	Software and hardware should conform to defined standards that promote interoperability for business processes_data_applications_and technology.	Standards help ensure consistency_thus improving the ability to manage systems and improve user satisfaction_and protect existing IT investments_thus maximizing return on investment and reducing costs. Standards for interoperability additionally help ensure support from multiple vendors for their products and facilitate supply chain integration.	1_Ministry is encouraged to adopt and comply with EA standards.\
2_Ministry must follow standards unless there is a compelling business reason to implement a non-standard solution. \
3_A process for setting standards_reviewing and revising them periodically_and granting exceptions must be established. \
4_The existing IT solutions must be identified_documented and rationalized to improve technology standardization.									1900-01-01	1900-01-01			1	umerkhan	2022-07-04	10:21:25	 	 	 	Create	1	\N	2022-07-04 10:21:25
15	Reuse before Buy		MIMEAPRINCIPLE015	Technology	High	Instead of starting from scratch_it is beneficial to adapt and enhance existing technology products_resources and approaches.	Reuse provides value for money by standardizing and simplifying the IT landscape_reducing data and technology duplication and adopting common business processes while bringing in global best practices.	1_Ministry needs to reduce the emphasis on program-centric silo funding and to leverage the use of ministry-level initiatives_capabilities and resources wherever practical.\
2_Sharing and reusing IT and information assets and services to support service delivery takes precedence over standalone and isolated systems\
3_Reuse of assets is preferred for purchasing new systems. Systems should be acquired with the future need of sharing and reuse in mind. Systems that enable sharing and reuse should_therefore_be preferred over systems for which reuse or sharing will be difficult.\
4_Buying new systems_or implementing non-standard solutions_is only undertaken as a last resort when there are clear and demonstrable business benefits.\
5_Ministry should enhance its ability to integrate applications and to provide common functions that could be leveraged by new applications.  Integration complexity should be reduced.\
6_Ministry needs to consider modifying its business processes_in conjunction with the use of unmodified COTS_for example_before implementing and modifying a new solution.									1900-01-01	1900-01-01			1	umerkhan	2022-07-04	10:21:25	 	 	 	Create	1	\N	2022-07-04 10:21:25
16	Business to Drive Technology Architecture		MIMEAPRINCIPLE016	Technology	High	The changes to technology architecture shall be me made in response to business needs and not the other way round.	This principle will foster an atmosphere where the IT changes in response to the needs of the business_rather than having the business change in response to IT changes. Therefore_involuntary effects on businesses resulting from IT changes are mitigated.\
However_technology changes can generate opportunities to improve and improvise the business process.\
	1_Changes in implementation should follow a full examination of the proposed changes using enterprise architecture.\
2_System development or technical improvement should not be implemented unless there is a documented business need.\
3_The business need must be given preference;however_it must also be aligned with other enterprise architecture principles. There must be a balance between business needs and IT operations.									1900-01-01	1900-01-01			1	umerkhan	2022-07-04	10:21:25	 	 	 	Create	1	\N	2022-07-04 10:21:25
17	Prefer Open Source Technology		MIMEAPRINCIPLE017	Technology	High	An open source approach to application and technology development can help to increase interoperability and collaboration in the digital development community and avoid duplicating work that has already been done by other organization.	Rationale Closed proprietary standards and software restrict reuse_reduce interoperability and can create vendor lock-in that leads to unforeseen financial costs.	1_Exit_rebid and rebuild costs must be taken into consideration during procurement decisions for the best value for money comparisons_between open source and proprietary solutions.\
2_Ministry should consider open-source software alongside commercial software equivalents from a total cost of ownership perspective.\
3_Ministry must ensure the availability of continuous support and maintenance for intended open source solutions.\
4_Ministry must evaluate open-source technology from the security perspective and must apply appropriate security controls to improve the security of the adopted open source technology.\
5_Open standards must be used in all solution designs to enable interoperability.									1900-01-01	1900-01-01			1	umerkhan	2022-07-04	10:21:25	 	 	 	Create	1	\N	2022-07-04 10:21:25
18	Scalability and Modularity		MIMEAPRINCIPLE018	Technology	High	Ministry technology_both hardware and software_architectures should be scalable_flexible and modular to meet ongoing and dynamic business growth.	Modular components have well-defined inputs and outputs.\
Loosely coupled components interoperate well but are not dependent on each other’s implementation specifics. \
Loose coupling is critical to achieving the graceful evolution of system function over time.\
	1_Standard scalability design patterns for each architectural domain should be published and periodically updated.\
2_A repository should be created to store modular components\
3_Component relationships need to be carefully designed early in the design cycle to ensure integration objectives are met while preserving loose coupling.\
4_Modular design is also a primary attribute leading to scalability. As demand varies_individual components can be added or removed to alter supply as needed. Furthermore_if there is a demand variance between different services_modular components can be shifted between services making the most of every resource. This is especially advantageous when using virtualization technology.									1900-01-01	1900-01-01			1	umerkhan	2022-07-04	10:21:25	 	 	 	Create	1	\N	2022-07-04 10:21:25
19	Interoperability		MIMEAPRINCIPLE019	Technology	High	Software_hardware_and management and development processes should conform to defined standards that promote interoperability for data_applications_and technology.	Interoperability enables flexibility_reusability and adaptability in sharing information_systems_and processes within the ministry and across government.\
Interoperability ensures support from multiple vendors for their products and facilitates flexible application integration.\
	1_Interoperability and industry standards must be followed unless there is a mandatory business reason to implement a non-standard solution.\
20 A process to establish standards_periodic revision_and exceptions must be established.\
3_Current IT platforms must be identified and documented.									1900-01-01	1900-01-01			1	umerkhan	2022-07-04	10:21:25	 	 	 	Create	1	\N	2022-07-04 10:21:25
20	Security by Design		MIMEAPRINCIPLE020	Information Security	High	Security is embedded into business_application_data and technology architecture.	The principle will ensure that security is realized at the enterprise level not just an IT issue.\
It will ensure the security risks are mitigated across all the landscapes business as well as IT and will ensure security is driven by the business and organizational priorities and issues.\
	1_Comprehensive security operating model is required to be developed across people process and technology.\
2_Additional processes will be required to design and develop for managing various aspects of security from Application_Data_Infrastructure_and business\
3_Clear principles for the security of Application_Infrastructure_Data and Business will be required during the solution design phase\
4_Additional governance will be required to set up to ensure security is embedded and practiced across the ministry.\
5_Tools procurement will be required to set up security practice across the whole landscape									1900-01-01	1900-01-01			1	umerkhan	2022-07-04	10:21:25	 	 	 	Create	1	\N	2022-07-04 10:21:25
21	Information is Secured		MIMEAPRINCIPLE021	Information Security	High	Information is protected based on the principle of availability_confidentiality_integrity and authenticity. Security adherence for data sharing will ensure applying the required criteria using the auditing system and monitoring tools.	While access to information is allowed for business reasons_sensitivities and propriety control is important to be safeguarded.\
Any unrestricted and free access raises the security risk for data and information to be misused and can jeopardize the business interest and integrity of the whole ministry.\
	1_Classification of data into confidential and non-confidential categories will be key process.\
2_The level of confidentiality can be reviewed and defined by data proprietors and functional teams.\
3_Data security should be an integral part of overall security governance.\
4_Security for data elements to be part of the design from the initial phase.\
5_Specific tools procurement will be required to set up security practice across the whole landscape.									1900-01-01	1900-01-01			1	umerkhan	2022-07-04	10:21:25	 	 	 	Create	1	\N	2022-07-04 10:21:25
22	Information is Classified		MIMEAPRINCIPLE022	Information Security	High	An information asset’s classification is determined by its value and risk.	A fundamental understanding of the value of an information asset to the business and the business risk if it is exposed_corrupted_or lost is essential to determining the appropriate strategies and investments to make for protecting and managing it.\
This also optimizes the security expenditure_provides justification of information security spending and mitigation of possible overspending.\
	1_Ministry’s information_data standards should be identified.\
2_Ministry must approve and enforce information and assets classification policy.\
3_Ministry must classify all valuable information and assets based on the adopted classification scheme.\
4_Information_data should be maintained in a separate data layer decoupled from applications.\
5_Ministry shall deploy appropriate security controls commensurate with information and assets classification.\
									1900-01-01	1900-01-01			1	umerkhan	2022-07-04	10:21:25	 	 	 	Create	1	\N	2022-07-04 10:21:25
